#!/bin/bash
gsutil cp  gs://malkania-bucket1/1 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/2 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/3 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/4 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/5 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/6 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/7 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/8 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/9 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket1/10 gs://malkania-placeholder/folder1
gsutil cp  gs://malkania-bucket2/11 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/12 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/13 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/14 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/15 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/16 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/17 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/18 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/19 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket2/20 gs://malkania-placeholder/folder2
gsutil cp  gs://malkania-bucket3/21 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/22 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/23 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/24 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/25 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/26 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/27 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/28 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/29 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket3/30 gs://malkania-placeholder/folder3
gsutil cp  gs://malkania-bucket4/31 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/32 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/33 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/34 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/35 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/36 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/37 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/38 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/39 gs://malkania-placeholder/folder4
gsutil cp  gs://malkania-bucket4/40 gs://malkania-placeholder/folder4

