#!/bin/bash
gsutil cp 1 gs://malkania-bucket1
gsutil cp 2 gs://malkania-bucket1
gsutil cp 3 gs://malkania-bucket1
gsutil cp 4 gs://malkania-bucket1
gsutil cp 5 gs://malkania-bucket1
gsutil cp 6 gs://malkania-bucket1
gsutil cp 7 gs://malkania-bucket1
gsutil cp 8 gs://malkania-bucket1
gsutil cp 9 gs://malkania-bucket1
gsutil cp 10 gs://malkania-bucket1
gsutil cp 11 gs://malkania-bucket2
gsutil cp 12 gs://malkania-bucket2
gsutil cp 13 gs://malkania-bucket2
gsutil cp 14 gs://malkania-bucket2
gsutil cp 15 gs://malkania-bucket2
gsutil cp 16 gs://malkania-bucket2
gsutil cp 17 gs://malkania-bucket2
gsutil cp 18 gs://malkania-bucket2
gsutil cp 19 gs://malkania-bucket2
gsutil cp 20 gs://malkania-bucket2
gsutil cp 21 gs://malkania-bucket3
gsutil cp 22 gs://malkania-bucket3
gsutil cp 23 gs://malkania-bucket3
gsutil cp 24 gs://malkania-bucket3
gsutil cp 25 gs://malkania-bucket3
gsutil cp 26 gs://malkania-bucket3
gsutil cp 27 gs://malkania-bucket3
gsutil cp 28 gs://malkania-bucket3
gsutil cp 29 gs://malkania-bucket3
gsutil cp 30 gs://malkania-bucket3
gsutil cp 31 gs://malkania-bucket4
gsutil cp 32 gs://malkania-bucket4
gsutil cp 33 gs://malkania-bucket4
gsutil cp 34 gs://malkania-bucket4
gsutil cp 35 gs://malkania-bucket4
gsutil cp 36 gs://malkania-bucket4
gsutil cp 37 gs://malkania-bucket4
gsutil cp 38 gs://malkania-bucket4
gsutil cp 39 gs://malkania-bucket4
gsutil cp 40 gs://malkania-bucket4

